import Title from './Title';
import Table from './Table';
import Painel from './Painel';
import Input from './Input';
import Label from './Label';
import Form from './Form';
import Fieldset from './Fieldset';
import Textarea from './Textarea';
import Button from './Button';
export {Title, Table, Painel, Input, Label, Form, Fieldset, Textarea, Button};
