import type { NextPage } from 'next'
import Head from 'next/head'
import { LoginPage } from '../src/components';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sitema hospitalar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage/>
    </div>
  )
}

export default Home
